name: Caladium Unit testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install requests flask pycouchdb requests
    - name: Run tests
      env:
        CALADIUM_SERVER_ADDRESS: 127.0.0.1:8080
        COUCHDB_CONNECTION_STR: ${{ secrets.COUCHDB_CONNECTION_STR }}
      run: |
        nohup python3 server/src/__main__.py &
        python3 -c "import time; time.sleep(3)"
        python3 -m unittest discover server/tests
